name: ML
channels:
  - conda-forge
dependencies:
  - transformers
  - datasets
  - scikit-learn
  - numpy
  - pytorch
  - tiktoken
  - sentencepiece
  - accelerate
  - protobuf
  - huggingface_hub[hf_xet]