# Use an official Python image as a base
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    curl \
    chromium \
    chromium-driver \
    firefox-esr \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

# Install GeckoDriver
RUN wget -q https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz \
    && tar -xvzf geckodriver-v0.36.0-linux64.tar.gz \
    && chmod +x geckodriver \
    && mv geckodriver /usr/local/bin/

# Install Selenium
RUN pip install --no-cache-dir selenium


COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy Selenium script to the container
COPY main.py /app/main.py
COPY selenium_helper.py /app/selenium_helper.py

EXPOSE 5000

# Set environment variables for Chrome
# ENV CHROME_BIN=/usr/bin/chromium
# ENV CHROMEDRIVER_BIN=/usr/bin/chromedriver
ENV MOZ_HEADLESS=1

# Run Selenium script
CMD ["python", "selenium_helper.py"]